### PR TITLE
Add getdllpath

### PR DESCRIPTION
**Pull request by onyx-and-iris**
Hi mate, great work on this wrapper!

Following additions:

Added getdllpath() to fetch path from registry.

updated examples to call .login() at script startup

updated readme

### CODE REVIEW

**Comment by SaifAqqad** [comment]
Thank you for the contribution.
I have a question though, why are you looping in the registry instead of just reading the `UninstallString` value

**Comment by onyx-and-iris** [comment]
hey dude, originally I wanted to loop through Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall to check for vmkey but was having a problem getting it working right, that's why the loop was there. (Since I wasn't sure if it would throw an error if the key was not present, in other languages I've experienced different behaviour). But since it's only reading key/values in vmkey then there is no need for the loop, feel free to remove it =).

I just thought it might make the wrapper a little more automated and simpler for users if it found the dllpath automatically.

This is my first time writing in autohotkey language.

**Comment by SaifAqqad** [comment]
> I just thought it might make the wrapper a little more automated and simpler for users if it found the dllpath automatically.

Yeah I agree, this is much better, but I'll keep the option to pass the path, so it's still usable in any case

**Comment by onyx-and-iris** [comment]
Ok great, yes that makes sense. I checked option to allow edits by maintainers so keep something you like and remove anything you don't. Thanks for checking out the pull request!

**Comment by SaifAqqad** [comment]
You can check out the changes I made, if it all looks good then I'll merge it right now.
Again thank you for the contribution :D

**Comment by onyx-and-iris** [comment]
Much cleaner! All looks good. Keep up the good work on this wrapper!

**Pull request merged**
